version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"          # where your pom.xml lives (root here)
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "main"
  - package-ecosystem: "maven"
    directory: "/core"          # where your pom.xml lives (root here)
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "main"
  - package-ecosystem: "maven"
    directory: "/rest"          # where your pom.xml lives (root here)
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "main"
  - package-ecosystem: "maven"
    directory: "/web"          # where your pom.xml lives (root here)
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "main"
